### ISSUE TITLE
txt file with utf-8 encoding won't upload

### ISSUE THREAD

**Issue by maayansharon10** [ncbi-nlp/TeamTat#34]
Hello, and thank you for this amazing product!
I was saving simple strings into a .txt file with a UTF8  format. when tried to upload them as documents I got an error.
When filtering out all non ascii values, tried to upload again and was successful.
not sure why not supporting utf-8 format. 
in some cases, ignoring non ascii changes the word so also changes the meaning.
Attaching screenshots and 2 example files I tried uploading.
Would appreciate your help,
Thank you again :) 

screenshot: 
![image](https://user-images.githubusercontent.com/64658737/211210896-37ca8b51-e427-4063-aa3f-87642a54ab04.png)

[document_ASCII_only.txt](https://github.com/ncbi-nlp/TeamTat/files/10369086/document_ASCII_only.txt)
[document_UTF8.txt](https://github.com/ncbi-nlp/TeamTat/files/10369087/document_UTF8.txt)

**Comment by dongseop** [comment]
I don't know exactly. However, I got an error " #<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT>" while processing the title of the UTF-8 document. So I add a force-encoding to the process. Please try it again and let me know if you have the same problem.

**Comment by maayansharon10** [comment]
Thank you!
