### ISSUE TITLE
Cannot login after logout

### ISSUE THREAD

**Issue by pedroruas18** [ncbi-nlp/TeamTat#39]
Hi

I've registered my email and created two annotation projects. However, after logout, I cannot access the created projects. 

I've checked my email account and I did not receive an email containing the original session URL. I've invited users and they also did not receive the session URL in their respective email accounts.

Is there any way of login without using the session URL?

Thank you

**Comment by almogmor** [comment]
I have the same issue.

**Comment by pedroruas18** [comment]
That works, thank you!
